# 180921 - ThinkPad T430s
export LC_ALL=en_US.UTF-8
export RESOLUTION_X=$(xdpyinfo | awk '/dimensions:/ { print $2; exit }' | cut -d 'x' -f 1)
export RESOLUTION_Y=$(xdpyinfo | awk '/dimensions:/ { print $2; exit }' | cut -d 'x' -f 2)
# INFO 200907: use '&' at the end if program will be ran longer and it is not a daemon (tint2, picom, ...)

hsetroot -solid '#000000'& #	x11 compositors cannot use xsetroot
setxkbmap -option "terminate:ctrl_alt_bksp"&
xrdb .xdefaults&
xbindkeys&
tint2&
xset r rate 250 30&
xinput set-prop "TPPS/2 IBM TrackPoint" "libinput Accel Speed" -0.35&		# using libinput instead of xf86-input-mouse
xinput disable "SynPS/2 Synaptics TouchPad"&
xmodmap .xmodmap&	# INFO 200907: must be after xinput commands (otherwise CapsLock and other remaps won't work)

# fix for T430s with fuck-up keyboard layout:
xmodmap -e "keycode 107 = Super_R"  # "PrtSc" key between Alt and Ctrl

unclutter --timeout 1&		# hide mouse pointer - no problem when hiding cursor on mpv
# hhpc -i 1&		# unclutter alterntive, works also on hw accelated videos XXX 181126: freezes mouse under cwm
# osdmixer 300 100 d d&
killall osdmixer; osdmixer $((RESOLUTION_X/4)) 100 d d&
volumeicon&

# sh ~/.opt/conky.sh&
# pcmanfm -n /mnt/local/video/music &

# start X11 compositor
picom --backend glx --vsync --inactive-dim 0.02 --fade-delta 3 --unredir-if-possible --menu-opacity=1.0 --frame-opacity=0.98 --inactive-opacity=0.98 --daemon

# fancy Alt-Tab program (window chooser)
skippy-xd --start-daemon&

# needed for automount notify:
xhost +local:&

# notification deamon
# dunst&

# enable auto lock on idle (also used by mod+l and lock on pointer in
# upper left corner)
# xautolock -locker 'sh -c "xset dpms 10 && slock && xset dpms 0"' \
  # -corners +000 -time 5 -cornerdelay 1 -cornerredelay 10 &

# Enable redshift
# redshift -l 48.13:11.57 &
# redshift -l 50:20 &

# INFO 190317: setting DPI
# xrandr --dpi 192&
# xrandr --dpi 96&
# xrandr --dpi 120&
xrandr --dpi 96 &
# xrdb -merge $HOME/.Xresources

# xterm -title tp.root -e 'echo tp root && su -l'&				# tp root
# exec xterm -title glavni -geometry 100x20+50+50 -e tmux
# exec xterm -title glavni -geometry 100x20+50+50 -e 'tmux new-session -d -s glavni -n Wcwm ; tmux send-keys -t glavni:Wcwm "cwm -vv" Enter; tmux attach -t glavni:Wcwm '

pkill ssh-agent
eval $(ssh-agent)

# xrandr --dpi 144
# 181107:
# exec $HOME/.opt/bin/cwm -vv
# exec $HOME/.opt/bin/aphelia
# 191028
exec openbox
